Restructure to make it work

diff --git a/src/oidc-tokensh/oidc-tokensh b/src/oidc-tokensh/oidc-tokensh
--- a/src/oidc-tokensh/oidc-tokensh
+++ b/src/oidc-tokensh/oidc-tokensh
@@ -7,13 +7,13 @@
 
 usage()
 {
+    echo "This tool is based on httokensh by Dave Dykstra."
+    echo ""
     echo "Usage: oidc-tokensh [-h] [oidc-token options] -- [command]"
     echo 
     echo "Runs oidc-agent and oidc-token with given options, starts the "
     echo "command, and runs oidc-token in the background as needed to "
     echo "renew the token until the command exits."
-    echo ""
-    echo "This tool is based on httokensh by Dave Dykstra."
     echo ""
     echo "Options:"
     echo "  -h, --help              show this help message and exit"
@@ -29,44 +29,38 @@ usage()
 } >&2
 
 if [ $# = 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    echo "[${LINENO}] You ran:  $0 $@"
     usage
 fi
 
 OIDC_TOKEN_ARGS=""
-COMMANDARGS=()
+CMND_ARGS=""
+ORIG_ARGS=""
 GOTSEP=false
 MINSECS=60
 GOTVERBOSE=false
 GOTOUTFILE=false
+START_RENEWER=false
+
 while [ $# -gt 0 ]; do
+    ORIG_ARGS="${ORIG_ARGS} ${1}"
     if $GOTSEP; then
-        COMMANDARGS+=("$1")
+        CMND_ARGS="${CMND_ARGS} ${1}"
     else
         case "$1" in
             -h|--help)          usage;                           exit 0 ;;
             --)                 GOTSEP=true                             ;;
-            --minsecs)          MINSECS=$2;                      shift  ;;
             -v|--verbose)       GOTVERBOSE=true                         ;;
-            -o|--outfile)       GOTOUTFILE=true OUTFILE=$2;      shift  ;;
-            --oidc)             OIDC_ID=$2;                      shift  ;;
+            --minsecs)          MINSECS=$2;                      ORIG_ARGS="${ORIG_ARGS} $2"; shift  ;;
+            -o|--outfile)       GOTOUTFILE=true OUTFILE=$2;      ORIG_ARGS="${ORIG_ARGS} $2"; shift  ;;
+            --oidc)             OIDC_ID=$2;                      ORIG_ARGS="${ORIG_ARGS} $2"; shift  ;;
+            --renewer)          START_RENEWER=true                      ;;
         esac
     fi
     shift
 done
 
-OIDC_TOKEN_ARGS="${OIDC_ID} -t ${MINSECS}"
-[ "${GOTVERBOSE}" == "true" ] && {
-    echo "OIDC_TOKEN_ARGS: ${OIDC_TOKEN_ARGS}"
-}
-
-if ! $GOTSEP; then
-    COMMANDARGS=("$SHELL")
-fi
-
-if [ ${#COMMANDARGS[@]} = 0 ]; then
-    COMMANDARGS=("$SHELL")
-fi
-
+#########################################################################
 get_bearer_token_file(){
     # Get BEARER_TOKEN_FILE according to WLCG Bearer Token Discovery (https://zenodo.org/records/3937438)
     RETVAL=""
@@ -95,7 +89,7 @@ get_bearer_token_file_orig(){
     if ${GOTOUTFILE}; then
         export BEARER_TOKEN_FILE="${OUTFILE}"
     fi
-    echo "${BEARER_TOKEN_FILE}"
+    echo "[${LINENO}] ${BEARER_TOKEN_FILE}"
 }
 
 decodejwt() {
@@ -106,10 +100,15 @@ decodejwt() {
 
 gettoken()
 {
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] running oidc-add ${OIDC_TOKEN_ARGS}"
+    }
+    oidc-add ${OIDC_TOKEN_ARGS}
     TOKEN=$(oidc-token ${OIDC_TOKEN_ARGS})
+    # TOKEN=$(oidc-token egi)
     RETVAL="$?"
     if [ $RETVAL != 0 ]; then
-        echo "oidc-token failed, $1" >&2
+        echo "[${LINENO}] oidc-token failed, $1" >&2
         exit $RETVAL
     fi
     echo "${TOKEN}" > "${BEARER_TOKEN_FILE}"
@@ -117,54 +116,70 @@ gettoken()
     TOKENJSON=$(decodejwt "${TOKEN}")
     RETVAL="$?"
     if [ $RETVAL != 0 ]; then
-        echo "decodejwt failed, $1" >&2
+        echo "[${LINENO}] decodejwt failed, $1" >&2
         exit $RETVAL
     fi
 
     EXP=$(echo "${TOKENJSON}"|jq .exp)
     NOW=$(date +%s)
     SLEEPSECS=$((EXP - MINSECS - NOW + 2))
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] SLEEPSECS: ${SLEEPSECS} -- \$2: $2"
+    }
     if [ "${SLEEPSECS}" -lt "$2" ]; then
-        echo "Calculated renewal time of $SLEEPSECS seconds is less than $2, $1"
+        echo "[${LINENO}] Calculated renewal time of $SLEEPSECS seconds is less than $2, $1"
         exit 1
     fi
 }
 
-BEARER_TOKEN_FILE=$(get_bearer_token_file)
-export BEARER_TOKEN_FILE
-
-# The first time it is possible to get a cached token that is barely
-# beyond the minsecs, so reduce the minimum to just 1 second
-gettoken "not running command" 1
-
-# enable job control so background processes get their own process group
-set -m
-
-[ "${GOTVERBOSE}" == "true" ] && {
-    echo "Bearer Token is at $BEARER_TOKEN_FILE"
-}
-echo "Renewal log is at \$BEARER_TOKEN_FILE.log"
-{
-    # keep a copy of $PPID because it will change to 1 if parent dies
-    PARENTPID=$PPID
-    [ "${GOTVERBOSE}" == "true" ] && {
-        echo oidc-token args are "${OIDC_TOKEN_ARGS}"
+start_agent(){
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] starting: >>oidc-agent -- /bin/bash -c "$0 --renewer ${ORIG_ARGS}"<<"
     }
-    while true; do
-        date
-        echo "Renewal scheduled in $SLEEPSECS seconds"
-        sleep $SLEEPSECS
-        date
-        if kill -0 $PARENTPID; then
-            gettoken "exiting" 60
-        else
-            echo "Parent process $PARENTPID not running, exiting"
-            exit 0
-        fi
-    done
-} >"${BEARER_TOKEN_FILE}.log" 2>&1 &
+    oidc-agent -- /bin/bash -c "$0 --renewer ${ORIG_ARGS}"
 
-BACKGROUND_PID=$!
+    # old and working:
+    # echo "[${LINENO}] starting: >>oidc-agent -- /bin/bash -c $0 --renewer --oidc egi<<"
+    # oidc-agent -- /bin/bash -c "$0 --renewer --oidc egi"
+}
+
+start_token_renewer() {
+    # enable job control so background processes get their own process group
+    gettoken "Initial" 2
+    set -m
+    {
+        exec 3>&1 1>>$BEARER_TOKEN_FILE.log
+        exec 4>&2 2>>$BEARER_TOKEN_FILE.log
+        trap cleanup 0
+        # keep a copy of $PPID because it will change to 1 if parent dies
+        PARENTPID=$PPID
+        [ "${GOTVERBOSE}" == "true" ] && {
+            echo "[${LINENO}] oidc-token args are ${OIDC_TOKEN_ARGS}"
+        }
+        while true; do
+            date
+            echo "Renewal scheduled in $SLEEPSECS seconds"
+            sleep $SLEEPSECS
+            date
+            if kill -0 $PARENTPID 2>/dev/null; then
+                gettoken "exiting" 60
+            else
+                echo "[${LINENO}] Parent process $PARENTPID not running, exiting"
+                echo "[${LINENO}]         mypid: $$"
+                exit 0
+            fi
+        done
+    } &
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] excuting: ${CMND_ARGS}"
+    }
+    # Start the actual shell
+    ${CMND_ARGS}
+
+    echo "$BEARER_TOKEN_FILE.log"
+    export BACKGROUND_PID=$!
+}
+#########################################################################
 
 cleanup()
 {
@@ -172,16 +187,48 @@ cleanup()
         wait 2>/dev/null
         rm -f "${BEARER_TOKEN_FILE}" "${BEARER_TOKEN_FILE}.log"
     else
-        echo >&2
-        echo "Renewal background process failed, see $BEARER_TOKEN_FILE.log" >&2
-        exit 1
+        # echo >&2
+        exec 1>&3 3>&-
+        exec 2>&4 4>&-
+        echo -e "\n\nRenewal background process failed to renew Access Token, see $BEARER_TOKEN_FILE.log\n"
+        echo "Renewal background process failed, see $BEARER_TOKEN_FILE.log" >> ${BEARER_TOKEN_FILE}.log
+        exit 2
     fi
 }
 
-trap cleanup 0
-
-[ "${GOTVERBOSE}" == "true" ] && {
-    echo "COMMAND: ${COMMANDARGS[*]}"
+OIDC_TOKEN_ARGS="${OIDC_ID} -t ${MINSECS}"
+[ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+    echo "[${LINENO}] OIDC_TOKEN_ARGS: ${OIDC_TOKEN_ARGS}"
 }
-# "${COMMANDARGS[@]}"
-oidc-agent "${COMMANDARGS[@]}"
+
+if ! $GOTSEP; then
+    CMND_ARGS="${SHELL}"
+fi
+
+BEARER_TOKEN_FILE=$(get_bearer_token_file)
+export BEARER_TOKEN_FILE
+
+
+[ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+    echo "[${LINENO}] Bearer Token is at $BEARER_TOKEN_FILE"
+}
+[ "${START_RENEWER}" == "false" ] && {
+    echo "Renewal log is at $BEARER_TOKEN_FILE.log"
+}
+
+[ "${START_RENEWER}" == "true" ] && {
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] Starting renewer"
+        echo "[${LINENO}] OIDC_TOKEN_ARGS: ${OIDC_TOKEN_ARGS}"
+    }
+    start_token_renewer
+    [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
+        echo "[${LINENO}] BACKGROUND_PID: ${BACKGROUND_PID}"
+    }
+}
+
+
+[ "${START_RENEWER}" == "false" ] && {
+    trap cleanup 0
+    start_agent
+}
