Adjust cleanup

diff --git a/src/oidc-tokensh/oidc-tokensh b/src/oidc-tokensh/oidc-tokensh
--- a/src/oidc-tokensh/oidc-tokensh
+++ b/src/oidc-tokensh/oidc-tokensh
@@ -158,7 +158,7 @@ start_token_renewer() {
             sleep $SLEEPSECS
             date
             if kill -0 $PARENTPID 2>/dev/null; then
-                gettoken "exiting" 60
+                gettoken "exiting" 10
             else
                 echo "[${LINENO}] Parent process $PARENTPID not running, exiting"
                 echo "[${LINENO}]         mypid: $$"
@@ -166,30 +166,27 @@ start_token_renewer() {
             fi
         done
     } &
+    export BACKGROUND_PID=$!
     [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
         echo "[${LINENO}] excuting: ${CMND_ARGS}"
     }
     # Start the actual shell
     ${CMND_ARGS}
 
-    echo "$BEARER_TOKEN_FILE.log"
-    export BACKGROUND_PID=$!
 }
 #########################################################################
 
 cleanup()
 {
-    if kill -- -"$BACKGROUND_PID" 2>/dev/null; then
-        wait 2>/dev/null
-        rm -f "${BEARER_TOKEN_FILE}" "${BEARER_TOKEN_FILE}.log"
-    else
-        # echo >&2
-        exec 1>&3 3>&-
-        exec 2>&4 4>&-
-        echo -e "\n\nRenewal background process failed to renew Access Token, see $BEARER_TOKEN_FILE.log\n"
-        echo "Renewal background process failed, see $BEARER_TOKEN_FILE.log" >> "${BEARER_TOKEN_FILE}.log"
-        exit 2
-    fi
+    [ -z "${BACKGROUND_PID}" ] || {
+        if kill -0 "$BACKGROUND_PID" 2>/dev/null; then
+            rm -f "${BEARER_TOKEN_FILE}" "${BEARER_TOKEN_FILE}.log"
+        else
+            echo -e "\n\nRenewal background process failed to renew Access Token, see $BEARER_TOKEN_FILE.log\n"
+            echo "Renewal background process failed, see $BEARER_TOKEN_FILE.log" >> "${BEARER_TOKEN_FILE}.log"
+            exit 2
+        fi
+    }
 }
 
 OIDC_TOKEN_ARGS="${OIDC_ID} -t ${MINSECS}"
@@ -217,6 +214,7 @@ export BEARER_TOKEN_FILE
         echo "[${LINENO}] Starting renewer"
         echo "[${LINENO}] OIDC_TOKEN_ARGS: ${OIDC_TOKEN_ARGS}"
     }
+    trap cleanup 0
     start_token_renewer
     [ "${GOTVERBOSE}" == "true" ] && [ "${START_RENEWER}" == "false" ] && {
         echo "[${LINENO}] BACKGROUND_PID: ${BACKGROUND_PID}"
@@ -225,6 +223,6 @@ export BEARER_TOKEN_FILE
 
 
 [ "${START_RENEWER}" == "false" ] && {
-    trap cleanup 0
+    # trap cleanup 0
     start_agent
 }
